### ISSUE TITLE
User should be able to edit the size of text 

### ISSUE THREAD

**Issue by jai-dewani** [jai-dewani/memeify#35]

**Comment by UnknownAbyss** [comment]
Hello. I would like to take up this issue. Can you explain how exactly you want the changes to function?

**Comment by jai-dewani** [comment]
Thanks for reaching out Additya,  
you can use this website for reference -> https://imgflip.com/memegenerator.  
Don't take it as me asking for a complete replica, but just a base point on how it should function >_<

**Comment by UnknownAbyss** [comment]
So do you just want me to add 2 buttons that let you increase/decrease text size?

**Comment by UnknownAbyss** [comment]
![image](https://user-images.githubusercontent.com/44570898/135746937-4284d329-c37c-48f1-8ec3-631dbf12684a.png)
I have implemented the feature for setting text size in pixels. You can go through it in the following commit :)

**Comment by UnknownAbyss** [comment]
Heya. Could you please take a look at my PR? Thanks ^_^

**Comment by jai-dewani** [comment]
This PR has introduced a new bug where the text is only draggable if the text is selected where it was originally before changing the resizing of text. It is now being tracked here #55
