### ISSUE TITLE
Add hover text for color input elements 

### ISSUE THREAD

**Issue by jai-dewani** [jai-dewani/memeify#44]
In displayMeme.js file 
- "Text Colour" for the first color input
- "Border Colour" for the second color input

**Comment by Yash-271120** [comment]
Hi, can you assign this issue to me. I know react but I am new to open source looking for contributions!

**Comment by jai-dewani** [comment]
Thanks for reaching out @Yash-271120!  
Yes, this still has to be fixed, so I am assigning this issue to you.

**Comment by Yash-271120** [comment]
@jai-dewani I think the bug is already been fixed. It works same as stated here #44

**Comment by jai-dewani** [comment]
Oh no, the hover text is still missing. There is no bug in the colour selection process, I just didn't want the users to get confused about which colour is for what, so I added this issue to have hover texts

**Comment by Yash-271120** [comment]
Ok I get it now!

**Comment by Likkiii** [comment]
Hello, I'd like to take this issue up.

**Comment by jai-dewani** [comment]
Thanks for reaching out Likhit 
Sure, I will assign this issue to you :)

**Comment by Likkiii** [comment]
Hello, it'd be really great if you could review my PR
Thanks :)

**Comment by jai-dewani** [comment]
This has been fixed with #53
